FROM node:16

WORKDIR /blog_web/
COPY . .

RUN npm i && npm run build

FROM nginx:alpine
LABEL MAINTAINER="SliverHorn@sliver_horn@qq.com"

COPY .docker-compose/nginx/conf.d/my.conf /etc/nginx/conf.d/my.conf
COPY --from=0 /blog_web/dist /usr/share/nginx/html